#!/usr/bin/env python3
"""
Print what the CloudFormation service supports, or regenerate the README table.

The facts come from ``ministack.services.cloudformation.capabilities``:
resource types with their verbs and the attributes their create handlers
return, API actions, intrinsics, pseudo parameters and the declared
template-feature support. A running emulator serves the same document at
``GET /_ministack/cfn/capabilities``.

The script imports that module from this checkout, which runs the
``ministack.services.cloudformation`` package ``__init__`` and so needs the
package's runtime dependencies installed (``requirements.txt``, for example
``defusedxml``). The tree named by ``--src`` is different: its source files are
only parsed with ``ast`` and never imported or executed, so the document
describes that tree even though the reader is this checkout's.

Usage:
    scripts/cfn_capabilities.py [--src ROOT] [--json] [--readme]

  --src     source root to read (default: this checkout)
  --json    print the capability document (default: a short summary)
  --readme  rewrite README.md's "Supported Resource Types" note and table in place
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from ministack.services.cloudformation.capabilities import build

TABLE_HEADING = "**Supported Resource Types:**"
# Written under the heading on every run, so the table cannot be read as AWS's
# attribute list: it is the emulator's, extracted from its create handlers.
TABLE_NOTE = (
    "Generated by `scripts/cfn_capabilities.py --readme`. The GetAtt column lists the attributes "
    "MiniStack's create handler returns for each type, which is what `Fn::GetAtt` resolves here. "
    "It is not AWS's GetAtt surface and is not checked against it: a type can offer an attribute "
    "AWS does not document, or lack one AWS has."
)
TABLE_HEADER = "| Resource Type | Ref Returns | GetAtt |"


def rewrite_readme(readme: Path, caps: dict) -> int:
    """Regenerate the resource table and the note above it; the human-written
    "Ref Returns" column is kept per type, new types get a neutral default."""
    text = readme.read_text()
    heading = text.index(TABLE_HEADING)
    start = text.index(TABLE_HEADER, heading)
    end = text.index("\n\n", start)
    ref_col: dict[str, str] = {}
    getatt_col: dict[str, str] = {}
    for row in text[start:end].splitlines()[2:]:
        cells = [c.strip() for c in row.strip("|").split("|")]
        if len(cells) >= 3:
            rtype = cells[0].strip("`").split("`")[0]
            ref_col[rtype] = cells[1]
            getatt_col[rtype] = cells[2]
    rows = []
    for rtype, info in sorted(caps["resource_types"].items()):
        ref = ref_col.get(rtype, "Physical resource id")
        if info["attributes"] is None:
            getatt = getatt_col.get(rtype, "*(template-dependent)*")
        else:
            getatt = ", ".join(info["attributes"]) or "\u2014"
        suffix = " (nested)" if rtype == "AWS::CloudFormation::Stack" else ""
        rows.append(f"| `{rtype}`{suffix} | {ref} | {getatt} |")
    lines = [TABLE_HEADING, "", TABLE_NOTE, "", TABLE_HEADER, "|---------------|-------------|--------|", *rows]
    new = text[:heading] + "\n".join(lines) + text[end:]
    if new != text:
        readme.write_text(new)
    return len(rows)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", default=str(REPO), help="ministack source root")
    ap.add_argument("--json", action="store_true", help="print the capability document")
    ap.add_argument("--readme", action="store_true", help="rewrite the README resource table")
    args = ap.parse_args(argv)
    src = Path(args.src).resolve()
    caps = build(src)
    if args.readme:
        n = rewrite_readme(src / "README.md", caps)
        print(f"README resource table regenerated: {n} rows", file=sys.stderr)
    if args.json:
        print(json.dumps(caps, indent=2, sort_keys=True))
        return 0
    types = caps["resource_types"]
    exact = sum(1 for t in types.values() if t["attributes_exact"])
    print(f"ministack {caps['ministack_version']}: {len(types)} resource types, "
          f"{sum(1 for t in types.values() if 'update' in t['verbs'])} with update, "
          f"{exact} with an exact attribute list, {len(caps['actions'])} actions, "
          f"{len(caps['intrinsics']['resolve'] or [])} intrinsics")
    for name, f in caps["features"].items():
        print(f"  {name:28s} {f['support']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
